trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool: Linux
      
    steps:
    - task: TerraformTaskV4@4
      displayName: Tf init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Raju-Subscription(a59439f4-ff80-4209-9405-5358d43e6066)'
        backendAzureRmResourceGroupName: 'raju-rg'
        backendAzureRmStorageAccountName: 'rajustg'
        backendAzureRmContainerName: 'prod-tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate
    
    - task: TerraformTaskV4@4
      displayName: tf fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'Raju-Subscription(a59439f4-ff80-4209-9405-5358d43e6066)'
    
    
    - task: TerraformTaskV4@4
      displayName: Tf plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out $(Build.SourcesDirectory)/tfplanfile'
        environmentServiceNameAzureRM: 'Raju-Subscription(a59439f4-ff80-4209-9405-5358d43e6066)'

    
    - task: ArchiveFiles@2
      displayName: Archivefiles
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      displayName: publishArtifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(Build.BuildId)-build'
        publishLocation: 'Container'